version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: cropguard-db
    environment:
      POSTGRES_DB: cropguard_db
      POSTGRES_USER: cropguard_user
      POSTGRES_PASSWORD: secure_password_2024
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - cropguard-network

  backend:
    build: ./backend
    container_name: cropguard-backend
    environment:
      DATABASE_URL: "postgresql://cropguard_user:secure_password_2024@postgres:5432/cropguard_db?schema=public"
      JWT_SECRET: "backend_jwt_secret_key_2024"
      PORT: 5000
      OPENWEATHER_API_KEY: "${OPENWEATHER_API_KEY}"
    ports:
      - "5002:5000"
    depends_on:
      - postgres
    networks:
      - cropguard-network
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: cropguard-frontend
    environment:
      NEXTAUTH_SECRET: "cropguard_secret_key_2024"
      NEXTAUTH_URL: "http://localhost:3001"
      DATABASE_URL: "postgresql://cropguard_user:secure_password_2024@postgres:5432/cropguard_db?schema=public"
      BACKEND_URL: "http://backend:5000"
      OPENWEATHER_API_KEY: "${OPENWEATHER_API_KEY}"
    ports:
      - "3001:3000"
    depends_on:
      - backend
      - postgres
    networks:
      - cropguard-network

volumes:
  postgres_data:

networks:
  cropguard-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16
